config/routes.rb
Spree::Core::Engine.routes.draw do
  get 'r/:code', to: 'reffiliate#referral', as: 'referral'
  get 'a/:path', to: 'reffiliate#affiliate', as: 'affiliate'
  get 'account/referral_details', to: 'users#referral_details'

  namespace :admin do
    resources :affiliates do
      resources :commissions do
        patch :pay, on: :member
      end
      get :transactions, on: :member
    end

    resource :referral_settings, only: [:edit, :update]

    resources :commission_rules
  end

  namespace :affiliate do
    resources :confirmations, only: [:new, :create]
  end
end

app/models/spree/referral_setting.rb
module Spree
  class ReferralSetting < Spree::Preference
  end
end

app/controllers/spree/admin/referral_settings_controller.rb
module Spree
  module Admin
    class ReferralSettingsController < ResourceController
      before_action :check_credit_amount, only: :update

      def update
        Spree::Config[:referrer_benefit_enabled] = params[:referrer_benefit_enabled] == '1'
        Spree::Config[:referral_credits] = params[:referral_credits]
        flash[:success] = Spree.t(:successful, scope: "referral_settings.update")
        redirect_to edit_admin_referral_settings_path
      end

      private

      def check_credit_amount
        if params[:referral_credits].to_f < 0
          flash[:error] = Spree.t(:unsuccessful, scope: "referral_settings.update")
          redirect_to edit_admin_referral_settings_path
        end
      end
    end
  end
end

app/views/spree/admin/referral_settings/edit.html.erb
<% content_for :title do %>
  <%= t('spree.name', scope: :referral_settings) %>
<% end %>

<% content_for :page_title do %>
  <%= t('spree.name', scope: :referral_settings) %>
<% end %>

<%= form_tag admin_referral_settings_path, method: :put do %>
  <div class="row">
    <div class="col-md-4" data-hook="referral_settings">
      <div class="form-group field">
        <%= label_tag 'referral_credits', t('spree.credits_to_be_awarded', scope: :referral_settings) %>
          <%= preference_field_tag :referral_credits, Spree::Config[:referral_credits], type: :text_field, class: 'form-control' %>
      </div>

      <div class="checkbox">
        <%= label_tag :referrer_benefit_enabled do %>
          <%= preference_field_tag :referrer_benefit_enabled, Spree::Config[:referrer_benefit_enabled], type: :boolean %>
          <%= t('spree.referral_credit_status', scope: :referral_settings) %>
        <% end %>
      </div>

      <div class="form-actions" data-hook="buttons">
        <%= button t('actions.update'), 'update' %>
      </div>
    </div>
  </div>
<% end %>