config/routes.rb
Spree::Core::Engine.routes.draw do
  get 'r/:code', to: 'reffiliate#referral', as: 'referral'
  get 'a/:path', to: 'reffiliate#affiliate', as: 'affiliate'
  get 'account/referral_details', to: 'users#referral_details'

  namespace :admin do
    resources :affiliates do
      resources :commissions do
        patch :pay, on: :member
      end
      get :transactions, on: :member
    end

    resource :referral_settings, only: [:edit, :update]

    resources :commission_rules
  end

  namespace :affiliate do
    resources :confirmations, only: [:new, :create]
  end
end

app/models/spree/commission.rb
module Spree
  class Commission < Spree::Base
    has_many :transactions, class_name: 'Spree::CommissionTransaction', dependent: :restrict_with_error
    belongs_to :affiliate, class_name: 'Spree::Affiliate'

    validates :start_date, :end_date, presence: true
    validate :cannot_mark_unpaid
    validate :eligiblity_of_dates
    validate :eligible_to_be_paid, if: [:paid_changed?, :paid]

    self.whitelisted_ransackable_associations = %w[affiliate]
    self.whitelisted_ransackable_attributes =  %w[start_date end_date paid]

    define_model_callbacks :mark_paid, only: :after

    after_mark_paid :lock_transactions

    def mark_paid!
      run_callbacks :mark_paid do
        update_attributes!(paid: true)
      end
    end

    def display_total
      currency = Spree::Config[:currency]
      Spree::Money.new(transactions.map(&:amount).compact.sum, { currency: currency })
    end

    def can_marked_paid?
      !Date.current.between?(start_date, end_date)
    end

    private
      def lock_transactions
        transactions.update_all(locked: true)
      end

      def cannot_mark_unpaid
        errors.add(:base, Spree.t(:cannot_mark_unpaid, scope: :commission)) if !paid? && paid_changed?
      end

      def eligiblity_of_dates
        if(start_date && end_date)
          errors.add(:base, Spree.t(:unsuitable_date_range, scope: :commission)) if (start_date > end_date)
          errors.add(:base, Spree.t(:dates_ineligible, scope: :commission)) if (start_date < Time.current.beginning_of_month || end_date > Time.current.end_of_month)
        else
          errors.add(:base, Spree.t(:dates_ineligible, scope: :commission))
        end
      end

      def eligible_to_be_paid
        errors.add(:base, Spree.t(:not_eligible, scope: [:commission, :paid])) if can_marked_paid?
      end
  end
end

app/controllers/spree/admin/commissions_controller.rb
module Spree
  module Admin
    class CommissionsController < ResourceController
      belongs_to 'spree/affiliate'

      def pay
        if @commission.mark_paid!
          flash[:success] = Spree.t(:mark_paid_successfully, scope: :commission)
        else
          flash[:error] = Spree.t(:mark_paid_failure, scope: :commission)
        end
        redirect_to admin_affiliate_commissions_path(@affiliate)
      end

      private
        def collection
          return @collection if defined?(@collection)
          params[:q] = {} if params[:q].blank?

          @collection = super
          @search = @collection.ransack(params[:q])
          @collection = @search.result.includes(:affiliate, :transactions).page(params[:page]).per(params[:per_page] || Spree::Config[:admin_commissions_per_page])
        end

    end
  end
end

app/views/spree/admin/commissions/index.html.erb
<% content_for :page_title do %>
  <%= t('spree.listing_commissions') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', t('spree.back_to_affilate'), edit_admin_affiliate_path(@affiliate), class: 'btn btn-default' %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_commissions_listing">

    <%= search_form_for @search, url: admin_affiliate_commissions_path(@affiliate) do |f| %>
      <%- locals = { f: f } %>
      <div class="row">
        <div class="date-range-filter col-md-8">
          <div class="form-group">
            <%= label_tag :start_date_gteq, t('spree.start_date_range') %>
            <div class="row no-padding-bottom">
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :start_date_gteq, class: 'datepicker datepicker-from form-control', value: params[:q][:start_date_gteq], placeholder: t('spree.start') %>
                  <span class="input-group-addon"><i class="icon icon-calendar"></i></span>
                </div>
              </div>
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :start_date_lteq, class: 'datepicker datepicker-to form-control', value: params[:q][:start_date_lteq], placeholder: t('spree.end') %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :affiliate_email_cont, t('spree.affiliate_email') %>
            <%= f.text_field :affiliate_email_cont, size: 15, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :paid, t('spree.status') %>
            <%= f.select :paid_eq, [['paid', 1], ['unpaid', 0]], { selected: params[:q][:paid_eq], include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>
      </div>
      <div data-hook="admin_products_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>


<% if @commissions.any? %>
  <table class="table" id="listing_commissions" data-hook>
    <thead>
      <tr data-hook="admin_commissions_index_headers">
        <th><%= sort_link @search,:start_date, Spree.t(:start_date), { default_order: "desc" }, {title: 'admin_commissions_start_date'} %></th>
        <th><%= sort_link @search,:end_date, Spree.t(:end_date), { default_order: "desc" }, {title: 'admin_commissions_end_date'} %></th>
        <th><%= Spree.t(:total) %></th>
        <th><%= sort_link @search, :transactions_count, Spree.t(:transactions), { default_order: "desc" }, {title: 'admin_commissions_transactions_count'} %></th>
        <th><%= sort_link @search, 'affiliate.email', Spree.t(:affiliate), { default_order: "desc" }, {title: 'admin_commissions_affiliate_email'} %></th>
        <th><%= sort_link @search, 'commission_paid', Spree.t(:status), { default_order: "desc" }, {title: 'admin_commissions_paid'} %></th>
        <th data-hook="admin_commissions_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @commissions.each do |commission|%>
        <tr id="<%= spree_dom_id commission %>" data-hook="admin_commissions_index_rows" class="<%= cycle('odd', 'even')%>">
          <td><%= pretty_time(commission.start_date) %></td>
          <td><%= pretty_time(commission.end_date) %></td>
          <td class='align-center'><%= commission.display_total %></td>
          <td><%= commission.transactions_count.to_i %></td>
          <td class='align-center'><%= commission.affiliate.email %></td>
          <td class='align-center'>
            <% status = commission.paid? ? 'Paid' : 'unpaid' %>
            <span class="label label-primary"><%= status %></span>
          </td>
          <td data-hook="admin_commissions_index_row_actions" class="actions">
            <%= button_link_to "", transactions_admin_affiliate_path(id: @affiliate.id, q: { commission_id_eq: commission.id }), class: 'with-tip btn-sm btn-primary', icon: 'stats' %>
          <% if !commission.paid? && commission.can_marked_paid? %>
            <%= button_link_to "", pay_admin_affiliate_commission_path(@affiliate, commission), class: 'with-tip btn-sm btn-success', icon: 'ok', method: :patch %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @commissions %>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Commission)) %>
  </div>
<% end %>