config/routes.rb
Spree::Core::Engine.routes.draw do
  get 'r/:code', to: 'reffiliate#referral', as: 'referral'
  get 'a/:path', to: 'reffiliate#affiliate', as: 'affiliate'
  get 'account/referral_details', to: 'users#referral_details'

  namespace :admin do
    resources :affiliates do
      resources :commissions do
        patch :pay, on: :member
      end
      get :transactions, on: :member
    end

    resource :referral_settings, only: [:edit, :update]

    resources :commission_rules
  end

  namespace :affiliate do
    resources :confirmations, only: [:new, :create]
  end
end

app/models/spree/affiliate.rb
module Spree
  class Affiliate < Spree::Base

    attr_accessor :user, :active_on_create

    has_many :referred_records
    has_many :transactions, class_name: 'Spree::CommissionTransaction', dependent: :restrict_with_error
    has_many :commissions, class_name: 'Spree::Commission', dependent: :restrict_with_error
    has_many :affiliate_commission_rules, class_name: 'Spree::AffiliateCommissionRule', inverse_of: :affiliate, dependent: :destroy
    has_many :commission_rules, through: :affiliate_commission_rules, class_name: 'Spree::CommissionRule'

    accepts_nested_attributes_for :affiliate_commission_rules, reject_if: :invalid_rule

    validates :name, :path, :email, presence: true
    validates :email, :path, uniqueness: { allow_blank: true }
    validates :email, length: { maximum: 254, allow_blank: true }, email: { allow_blank: true }
    validates_associated :affiliate_commission_rules

    before_create :create_user, :process_activation
    after_commit :send_activation_instruction, on: :create

    self.whitelisted_ransackable_attributes =  %w[name email]

    def self.layout_options
      [
        ["No Layout", "false"],
        ["Spree Application Layout", 'spree/layouts/spree_application'],
        ["Custom Layout Path", nil]
      ]
    end

    def self.lookup_for_partial lookup_context, partial
      lookup_context.template_exists?(partial, ["spree/affiliates"], false)
    end

    def referred_users
      referred_records.includes(:user).collect(&:user).compact
    end

    def referred_orders
      order_ids = transactions.where(commissionable_type: 'Spree::Order').pluck(:commissionable_id)
      Spree::Order.where(id: order_ids)
    end

    def referred_count
      referred_records.count
    end

    def get_layout
      layout == 'false' ? false : layout
    end

    def referred_orders_count
      transactions.where(commissionable_type: 'Spree::Order').count
    end

    private

      def create_user
        @user = Spree::User.find_or_initialize_by(username: username)
        self.active_on_create = true
        affiliate_role = Spree::Role.affiliate
        user.spree_roles << affiliate_role unless user.spree_roles.include?(affiliate_role)
        user.save
      end

      def generate_activation_token
        self.activation_token = SecureRandom.hex(10)
      end

      def process_activation
        if active_on_create
          self.activation_token, self.active, self.activated_at = nil, true, Time.current
        else
          generate_activation_token
        end
      end

      def send_activation_instruction
        Spree::AffiliateMailer.activation_instruction(username).deliver_later
      end

      def invalid_rule(attributes)
        !attributes[:id] && !attributes[:rate].present? && !attributes[:active].eql?('1')
      end

  end
end

app/controllers/spree/admin/affiliates_controller.rb
module Spree
  module Admin
    class AffiliatesController < ResourceController
      helper_method :affiliate_partial_exists?
      before_action :layout_options, only: [:new, :create, :edit, :update]
      before_action :build_or_load_affiliate_commission_rule, only: [:new, :edit]

      def index
        @affiliates = Affiliate.all.page(params[:page]).per(params[:per_page] || Spree::Config[:admin_affiliates_per_page])
      end

      def transactions
        params[:q] = {} unless params[:q]
        @commission_transactions = @affiliate.transactions
        @search = @commission_transactions.ransack(params[:q])
        @commission_transactions = @search.result.page(params[:page]).per(params[:per_page] || Spree::Config[:admin_transactions_per_page])
      end

      protected

        def affiliate_partial_exists? partial
          return false if partial.blank?
          Affiliate.lookup_for_partial lookup_context, partial
        end

        def layout_options
          @layout_options = Spree::Affiliate.layout_options
        end

      private
      def build_or_load_affiliate_commission_rule
        Spree::CommissionRule.all.map { |comm_rule| @affiliate.affiliate_commission_rules.find_or_initialize_by(commission_rule_id: comm_rule.id) }
      end
    end
  end
end

app/controllers/spree/affiliate/confirmations_controller.rb
module Spree
  class Affiliate::ConfirmationsController < UsersController

    prepend_before_action :load_object, :load_affiliate, only: [:new, :create]

    def new
      redirect_to root_path, error: Spree(:not_found, scope: :affiliate_confirmation) unless @affiliate
    end

    def create
      @user.can_activate_associated_partner = true
      if @user.update_attributes(user_params)
        if params[:user][:password].present?
          sign_in(@user, :event => :authentication, :bypass => !Spree::Auth::Config[:signout_after_password_change])
        end
        redirect_to spree.account_url, :notice => Spree.t(:account_updated)
      else
        render :edit
      end
    end


    private
      def load_affiliate
        @affiliate = Spree::Affiliate.find_by(activation_token: params[:activation_token])
        redirect_to root_path, error: Spree.t(:activation_token_expired) unless @affiliate
      end

      def load_object
        @user = User.find_by(email: @affiliate.email)
        redirect_to root_path, error: Spree.t(:user_not_found) unless @user
      end
  end
end

app/views/spree/admin/affiliates/_form.html.erb
<div data-hook="admin_user_form_fields">
  <div class="row">
    <div class="col-md-12">
      <div data-hook="affiliate_name">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, t('spree.name') %>
          <%= f.text_field :name, class: 'form-control' %>
          <%= error_message_on :user, :name %>
        <% end %>
      </div>

       <div data-hook="affiliate_username">
        <%= f.field_container :username, class: ['form-group'] do %>
          <%= f.label :username, 'Username' %>
          <%= f.text_field :username, class: 'form-control' %>
          <%= f.error_message_on :username %>
        <% end %>
      </div>

      <div data-hook="affiliate_email">
        <%= f.field_container :email, class: ['form-group'] do %>
          <%= f.label :email, t('spree.email') %>
          <%= f.text_field :email, class: 'form-control' %>
          <%= f.error_message_on :email %>
        <% end %>
      </div>

      <div data-hook="affiliate_partial">
        <%= f.field_container :partial, class: ['form-group'] do %>
          <%= f.label :partial, t('spree.partial') + " (leave blank if no partial) " %>
          <p><%= t('spree.affiliate_partial_path') %> <%= f.text_field :partial, class: 'form-control' %></p>
          <%= f.error_message_on :partial %>
        <% end %>
      </div>

      <div data-hook="affiliate_path">
        <%= f.field_container :path, class: ['form-group'] do %>
          <%= f.label :path, t('spree.path') %>
          <%= f.text_field :path, class: 'form-control' %>
          <%= f.error_message_on :path %>
        <% end %>
      </div>

      <div data-hook="affiliate_layout">
        <%= f.field_container :layout, class: ['form-group'] do %>
          <%= f.label :layout, t('spree.layout') %>
          <%= select_tag 'fake_layout', options_for_select(@layout_options, selected: @affiliate.layout), class: "select2 #{'other' unless @layout_options.flatten.include?(@affiliate.layout)}" %>
          <p>
            <br/>
            <%= f.text_field :layout, value: @affiliate.layout.nil? ? @layout_options.first : @affiliate.layout, class: 'form-control' %>
          </p>
          <%= f.error_message_on :layout %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <fieldset data-hook="admin_affiliate_edit_general_settings" class="alpha twelve columns">
    <legend><%= Spree.t(:commission_info) %></legend>
      <%= f.fields_for :affiliate_commission_rules  do |aff_comm_rule| %>
        <% rule = aff_comm_rule.object.commission_rule %>
        <div class="col-md-6">
          <div data-hook="affiliate_commission">
            <%= aff_comm_rule.label :rate, "#{ rule.name } (#{rule.fixed_commission? ? 'fixed commission' : '% commission'})" %>
            <%= aff_comm_rule.text_field :rate, class: 'form-control' %>
            <%= aff_comm_rule.hidden_field :commission_rule_id %>
          </div>
        </div>
        <div class="col-md-6">
          <%= aff_comm_rule.label :active, :active %>
          <%= aff_comm_rule.check_box :active, class: 'form-control' %>
        </div>
      <% end %>
    </fieldset>
  </div>
</div>
<script>
  var fake_layout = $("#fake_layout"),
      affiliate_layout = $("#affiliate_layout");
  fake_layout.on("change", function(){
    affiliate_layout.hide();
    if ($(this).val() != '') {
      affiliate_layout.val($(this).val());
    } else {
      affiliate_layout.val('layouts/application').show().focus();
    }
  });
  if (!fake_layout.hasClass('other')) {
    affiliate_layout.hide();
  } else {
    fake_layout.val('');
  }
</script>

app/views/spree/admin/affiliates/edit.html.erb
<% content_for :page_title do %>
  <%= link_to "#{t('spree.editing_affiliate')} #{@affiliate.name}", edit_admin_affiliate_url(@affiliate) %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', t('spree.back_to_affiliates_list'), admin_affiliates_path, class: 'btn btn-default' %>
<% end %>

<fieldset data-hook="admin_affiliate_edit_general_settings" class="alpha twelve columns">
  <legend><%= t('spree.general_settings') %></legend>

  <div data-hook="admin_affiliate_edit_form_header">
    <%= render partial: 'spree/shared/error_messages', locals: { target: @affiliate } %>
  </div>

  <div data-hook="admin_affiliate_edit_form">
    <%= form_for [:admin, @affiliate], as: :affiliate, url: admin_affiliate_url(@affiliate), method: :put do |f| %>
      <%= render partial: 'form', locals: { f: f } %>

      <div data-hook="admin_affiliate_edit_form_button">
        <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: admin_affiliates_url } %>
      </div>
    <% end %>
  </div>
</fieldset>
<br/>
<fieldset data-hook="admin_affiliate_edit_stats" class="alpha twelve columns">
  <legend><%= t('spree.statistics') %></legend>
  <table class='table'>
    <tbody>
      <tr>
        <th>Affiliate hyperlink</th>
        <td><%= text_field_tag nil, affiliate_url(@affiliate.path), onclick: 'this.select();', class: 'form-control' %></td>
      </tr>
      <tr>
        <th>Partial Status</th>
        <% if @affiliate.partial.blank? or !affiliate_partial_exists?(@affiliate.partial) %>
          <td style="color: red">Not found</td>
        <% elsif affiliate_partial_exists?(@affiliate.partial) %>
          <td style="color: green">Found</td>
        <% end %>
      </tr>
      <tr>
        <th>Referred users</th>
        <td><%= @affiliate.referred_count %></td>
      </tr>
      <tr>
        <th>Referred orders</th>
        <td><%= @affiliate.referred_orders_count %></td>
      </tr>
      <tr>
        <th>Orders referred</th>
        <td>
          <%= "No referred orders" if @affiliate.referred_orders.count == 0 %>
          <ol style="margin-left: 20px;">
            <% @affiliate.referred_orders.each do |order| %>
              <li><%= link_to [order.number, order.email].join(', '), edit_admin_order_url(order) %></li>
            <% end %>
          </ol>
        </td>
      <tr>
      <tr>
        <th>Users referred</th>
        <td>
          <%= "No referred users" if @affiliate.referred_count == 0 %>
          <ol style="margin-left: 20px;">
            <% @affiliate.referred_users.each do |user| %>
              <li><%= link_to user.email, edit_admin_user_url(user) %></li>
            <% end %>
          </ol>
        </td>
      <tr>
    </tbody>
  </table>
</fieldset>

app/views/spree/admin/affiliates/index.html.erb
<% content_for :page_title do %>
  <%= t('spree.listing_affiliates') %>
<% end %>

<% content_for :page_actions do %>
  <span id="new_affiliate_section">
    <%= button_link_to t('spree.new_affiliate'), new_admin_affiliate_url, icon: 'add', class: "btn-success", id: 'admin_new_affiliate_link' %>
  </span>
<% end %>
<% if @affiliates.any? %>
  <table class="table" id="listing_affiliates" data-hook>
    <thead>
      <tr data-hook="admin_affiliates_index_headers">
        <th><%= t('spree.name') %></th>
        <th><%= t('spree.path') %></th>
        <th><%= t('spree.count') %></th>
        <th><%= t('spree.partial_status') %></th>
        <th data-hook="admin_affiliates_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @affiliates.each do |affiliate|%>
        <tr id="<%= spree_dom_id affiliate %>" data-hook="admin_affiliates_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class='affiliate_name'><%=link_to affiliate.name, edit_admin_affiliate_url(affiliate) %></td>
          <td class='affiliate_path align-center'><%= affiliate_url(affiliate.path) %></td>
          <td class='affiliate_count align-center'><%= affiliate.transactions.count %></td>
          <% if affiliate.partial.blank? || !affiliate_partial_exists?(affiliate.partial) %>
            <td class='affiliate_status align-center' style="color: red">Not found</td>
          <% elsif affiliate_partial_exists?(affiliate.partial) %>
            <td class='affiliate_status align-center' style="color: green">Found</td>
          <% end %>
          <td data-hook="admin_affiliates_index_row_actions" class="actions">

            <%= link_to_edit affiliate, no_text: true %>
            <%= button_link_to "", transactions_admin_affiliate_path(affiliate), { class: 'with-tip btn-sm btn-primary', icon: 'stats', data: { 'original-title': 'transactions' } } %>
            <%= button_link_to "", admin_affiliate_commissions_path(affiliate), { class: 'with-tip btn-sm btn-primary', icon: 'briefcase', data: { 'original-title': 'commissions' } } %>
            <%= link_to_delete affiliate, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @affiliates %>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= t('spree.no_resource_found', resource: plural_resource_name(Spree::Affiliate)) %>,
    <%= link_to(t('spree.add_one'), spree.new_admin_affiliate_path) if can? :create, Spree::Affiliate %>!
  </div>
<% end %>

app/views/spree/admin/affiliates/new.html.erb
<% content_for :page_title do %>
  <%= t('spree.new_affiliate') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', t('spree.back_to_affiliates_list'), admin_affiliates_path, class: 'btn btn-default' %>
<% end %>

<div data-hook="admin_affiliate_new_form_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @affiliate } %>
</div>

<div data-hook="admin_affiliate_new_form">
  <%= form_for [:admin, @affiliate], url: admin_affiliates_url, method: :post do |f| %>
    <%= render partial: 'form', locals: { f: f } %>

    <div data-hook="admin_affiliate_new_form_buttons">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/affiliates/transactions.html.erb
<% content_for :page_title do %>
  <%= t('spree.listing_commission_transactions') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', t('spree.back_to_affiliates_list'), admin_affiliates_path, class: 'btn btn-default' %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_transactions_search">
    <%= search_form_for @search, url: transactions_admin_affiliate_path(@affiliate) do |f| %>
      <%- locals = { f: f } %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :amount_eq, t('spree.amount') %>
            <%= f.text_field :amount_eq, size: 15, class: "form-control js-quick-search-target" %>
          </div>
        </div>
      </div>
      <div data-hook="admin_products_index_search_buttons" class="form-actions">
        <%= button t('spree.search'), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>


<% if @commission_transactions.any? %>
  <table class="table" id="listing_affiliates" data-hook>
    <thead>
      <tr data-hook="admin_affiliates_index_headers">
        <th><%= t('spree.reference) %></th>
        <th><%= t('spree.type') %></th>
        <th>
          <%= sort_link @search, :created_at, t('spree.date'), { default_order: "desc" }, {title: 'admin_transaction_listing_created_at'} %>
        </th>
        <th><%= sort_link @search, :amount, t('spree.amount'), { default_order: "desc" }, {title: 'admin_products_listing_amount'} %></th>
        <th><%= t('spree.locked') %></th>
      </tr>
    </thead>
    <tbody>
      <% @commission_transactions.each do |transaction|%>
        <tr id="<%= spree_dom_id transaction %>" data-hook="admin_transactions_index_rows" class="<%= cycle('odd', 'even')%>">
          <% if transaction.commissionable_type.eql? 'User' %>
            <td class='transaction_name'><%=link_to transaction.commissionable.email, admin_user_path(User.find_by(email: transaction.commissionable.email).try(:id)) %></td>
          <% elsif transaction.commissionable_type.eql? 'Spree::Order' %>
            <td class='transaction_name'><%=link_to transaction.commissionable.number, edit_admin_order_path(Spree::Order.find_by(number: transaction.commissionable.number).try(:number)) %></td>
          <% end %>
          <td class='transaction_name'><%= transaction.commissionable_type %></td>
          <td class='align-center'><%= pretty_time(transaction.created_at) %></td>
          <td class='align-center'><%= transaction.display_total %></td>
          <td class='align-center'> <%= transaction.locked? %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @commission_transactions %>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= t('spree.no_resource_found', resource: plural_resource_name(Spree::CommissionTransaction)) %>
  </div>
<% end %>