config/routes.rb
Spree::Core::Engine.routes.draw do
  get 'r/:code', to: 'reffiliate#referral', as: 'referral'
  get 'a/:path', to: 'reffiliate#affiliate', as: 'affiliate'
  get 'account/referral_details', to: 'users#referral_details'

  namespace :admin do
    resources :affiliates do
      resources :commissions do
        patch :pay, on: :member
      end
      get :transactions, on: :member
    end

    resource :referral_settings, only: [:edit, :update]

    resources :commission_rules
  end

  namespace :affiliate do
    resources :confirmations, only: [:new, :create]
  end
end

app/models/spree/commission_rule.rb
module Spree
  class CommissionRule < Spree::Base
    USER_REGISTRATION = 'User Registration'
    ORDER_PLACEMENT = 'Order Placement'
    has_many :affiliate_commission_rules, dependent: :restrict_with_error

    validates :name, presence: true

    def self.user_registration
      find_by(name: USER_REGISTRATION)
    end

    def self.order_placement
      find_by(name: ORDER_PLACEMENT)
    end
  end
end

app/controllers/spree/admin/commission_rules_controller.rb
module Spree
  module Admin
    class CommissionRulesController < ResourceController
    end
  end
end

app/views/spree/admin/commission_rules/_form.html.erb
<div data-hook="admin_user_form_fields">
  <div class="row">
    <div class="col-md-12">
      <div data-hook="commission_rule_name">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, t('spree.name') %>
          <%= f.text_field :name, class: 'form-control' %>
        <% end %>
      </div>

      <div data-hook="commission_rule_description">
        <%= f.field_container :description, class: ['form-group'] do %>
          <%= f.label :description, t('spree.description') %>
          <%= f.text_area :description, class: 'form-control' %>
        <% end %>
      </div>

      <div data-hook="commission_rule_fixed_commission">
        <%= f.field_container :fixed_commission, class: ['form-group'] do %>
          <%= f.label :fixed_commission, t('spree.fixed_commission') %>
          <%= f.check_box :fixed_commission, class: 'form-control' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/commission_rules/edit.html.erb
<% content_for :page_title do %>
  <%= t('spree.edit_commission_rule') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', t('spree.back_to_commission_rules_list'), admin_commission_rules_path, class: 'btn btn-default' %>
<% end %>

<div data-hook="admin_commission_rule_edit_form_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @commission_rule } %>
</div>

<div data-hook="admin_commission_rule_edit_form">
  <%= form_for [:admin, @commission_rule], url: admin_commission_rules_url, method: :post do |f| %>
    <%= render partial: 'form', locals: { f: f } %>

    <div data-hook="admin_commission_rule_edit_form_buttons">
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/commission_rules/index.html.erb
<% content_for :page_title do %>
  <%= t('spree.listing_commission_rules') %>
<% end %>

<% content_for :page_actions do %>
  <span id="new_affiliate_section">
    <%= button_link_to t('spree.new_commission_rule'), new_admin_commission_rule_url, icon: 'add', class: "btn-success", id: 'admin_new_commission_rule_link' %>
  </span>
<% end %>
<% if @commission_rules.any? %>
  <table class="table" id="listing_affiliates" data-hook>
    <thead>
      <tr data-hook="admin_affiliates_index_headers">
        <th><%= t('spree.name') %></th>
        <th><%= t('spree.description') %></th>
        <th><%= t('spree.fixed_commission') %></th>
        <th data-hook="admin_affiliates_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @commission_rules.each do |commission_rule|%>
        <tr id="<%= spree_dom_id commission_rule %>" data-hook="admin_commission_rules_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class='commission_rule_name'><%=link_to commission_rule.name, edit_admin_commission_rule_url(commission_rule) %></td>
          <td class='commission_rule_path align-center'><%= commission_rule.description %></td>
          <td class='commission_rule_count align-center'><%= commission_rule.fixed_commission? %></td>
          <td data-hook="admin_commission_rules_index_row_actions" class="actions">
            <%= link_to_edit commission_rule, no_text: true %>
            <%= link_to_delete commission_rule, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= t('spree.no_resource_found', resource: plural_resource_name(Spree::CommissionRule)) %>,
    <%= link_to(t('spree.add_one'), spree.new_admin_affiliate_path) if can? :create, Spree::CommissionRule %>!
  </div>
<% end %>

app/views/spree/admin/commission_rules/new.html.erb
<% content_for :page_title do %>
  <%= t('spree.new_commission_rule') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', t('spree.back_to_commission_rules_list'), admin_commission_rules_path, class: 'btn btn-default' %>
<% end %>

<div data-hook="admin_commission_rule_new_form_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @commission_rule } %>
</div>

<div data-hook="admin_commission_rule_new_form">
  <%= form_for [:admin, @commission_rule], url: admin_commission_rules_url, method: :post do |f| %>
    <%= render partial: 'form', locals: { f: f } %>

    <div data-hook="admin_commission_rule_new_form_buttons">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  <% end %>
</div>